import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'about',
  title: 'About',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero Section', default: true},
    {name: 'about', title: 'About Section'},
    {name: 'resume', title: 'Resume'},
  ],
  fields: [
    defineField({
      name: 'language',
      title: 'Language',
      type: 'string',
      options: {list: [{title: 'English', value: 'en'}, {title: 'Norsk', value: 'nb'}], layout: 'radio'},
      initialValue: 'en',
      description: 'Which language this document is written in. Leave as English unless this IS the Norwegian version.',
    }),
    defineField({
      name: 'translationOf',
      title: 'Translation of',
      type: 'reference',
      to: [{type: 'about'}],
      description: 'On a Norwegian document, point this at the English original. Leave empty on English documents.',
      hidden: ({document}) => document?.language !== 'nb',
    }),
    defineField({
      name: 'heading',
      title: 'Heading',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
      description: 'Main heading shown in the hero section',
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
      description: 'Short description below the heading',
    }),
    defineField({
      name: 'roles',
      title: 'Animated Roles',
      type: 'array',
      of: [{type: 'string'}],
      group: 'hero',
      description: 'Roles that cycle with a typing animation (e.g. ".NET Developer", "Homelab Enthusiast")',
    }),
    defineField({
      name: 'profileImage',
      title: 'Profile Image',
      type: 'image',
      options: {hotspot: true},
      group: 'hero',
      description: 'Displayed as a circle in the hero section. Square images work best.',
    }),
    defineField({
      name: 'heroCta1Text',
      title: 'Primary CTA Text',
      type: 'string',
      group: 'hero',
      description: 'e.g. "See my work"',
    }),
    defineField({
      name: 'heroCta1Link',
      title: 'Primary CTA Link',
      type: 'string',
      group: 'hero',
      description: 'e.g. "/#projects"',
    }),
    defineField({
      name: 'heroCta2Text',
      title: 'Secondary CTA Text',
      type: 'string',
      group: 'hero',
      description: 'e.g. "Get in touch"',
    }),
    defineField({
      name: 'heroCta2Link',
      title: 'Secondary CTA Link',
      type: 'string',
      group: 'hero',
      description: 'e.g. "/contact"',
    }),
    defineField({
      name: 'body',
      title: 'About Text',
      type: 'array',
      of: [{type: 'block'}],
      group: 'about',
      description: 'Rich text content for the About Me section',
    }),
    defineField({
      name: 'resumeFile',
      title: 'Resume / CV',
      type: 'file',
      group: 'resume',
      description: 'PDF file — a download button will appear in the hero section',
    }),
  ],
  preview: {
    select: {
      title: 'heading',
      media: 'profileImage',
    },
  },
})
