import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'pageContent',
  title: 'Page Content',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'contact', title: 'Contact Page'},
    {name: 'services', title: 'Services Page'},
  ],
  fields: [
    defineField({
      name: 'heroEyebrow',
      title: 'Hero Eyebrow Text',
      type: 'string',
      group: 'hero',
      description: 'Small text above the name (e.g. "Freelance Backend Engineer")',
    }),
    defineField({
      name: 'heroTagline',
      title: 'Hero Tagline',
      type: 'text',
      rows: 2,
      group: 'hero',
      description: 'Value proposition below the name',
    }),
    defineField({
      name: 'heroCta1Text',
      title: 'Primary CTA Text',
      type: 'string',
      group: 'hero',
      description: 'e.g. "See my work"',
    }),
    defineField({
      name: 'heroCta1Link',
      title: 'Primary CTA Link',
      type: 'string',
      group: 'hero',
      description: 'e.g. "/#projects"',
    }),
    defineField({
      name: 'heroCta2Text',
      title: 'Secondary CTA Text',
      type: 'string',
      group: 'hero',
      description: 'e.g. "Get in touch"',
    }),
    defineField({
      name: 'heroCta2Link',
      title: 'Secondary CTA Link',
      type: 'string',
      group: 'hero',
      description: 'e.g. "/contact"',
    }),
    defineField({
      name: 'contactHeading',
      title: 'Contact Page Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactIntro',
      title: 'Contact Page Intro',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'hireHeading',
      title: 'Hire Section Heading',
      type: 'string',
      group: 'contact',
      description: 'e.g. "Start a Project"',
    }),
    defineField({
      name: 'hireDescription',
      title: 'Hire Section Description',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'hireBullets',
      title: 'Hire Section Bullet Points',
      type: 'array',
      of: [{type: 'string'}],
      group: 'contact',
      description: 'What to include in project inquiry',
    }),
    defineField({
      name: 'hireButtonText',
      title: 'Hire Button Text',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'responseTime',
      title: 'Response Time Text',
      type: 'string',
      group: 'contact',
      description: 'e.g. "Typically responds within 24 hours"',
    }),
    defineField({
      name: 'helloHeading',
      title: 'Hello Section Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'helloDescription',
      title: 'Hello Section Description',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'helloButtonText',
      title: 'Hello Button Text',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'servicesHeading',
      title: 'Services Page Heading',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesIntro',
      title: 'Services Page Intro',
      type: 'text',
      rows: 3,
      group: 'services',
    }),
    defineField({
      name: 'servicesCta',
      title: 'Services Bottom CTA Heading',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesCtaDescription',
      title: 'Services Bottom CTA Description',
      type: 'text',
      rows: 3,
      group: 'services',
    }),
  ],
  preview: {
    prepare() {
      return {title: 'Page Content'}
    },
  },
})
